run:
  entry: main_multi_GPU.py
  python: python3

env:
  HF_HOME: ./cache/hf_home
  OPENCLIP_CACHE_DIR: ./cache/hf_home

args:
  dataset_path: datasets/downloads
  dataset_name: tinyimagenet
  model_name: resnet18
  image_size: 64
  pretrained: false
  optimizer_name: sgd
  lr: 0.01
  amp_enabled: true
  amp_dtype: bf16
  alpha: 0.1
  data_sampling_mode: fixed
  node_datasize: 512
  gossip_topology: random
  r_schedule: fixed
  r_start: 0.2
  r_end: 0.2
  num_nodes: 8
  num_GPU: 2
  k_steps: 10
  max_steps: 500
  batch_size: 64
  weight_decay: 0.0005
  nonIID: true
  window_size: 0.05
  point1: 0.9
  lr_scheduler: none
  post_merge_rounds: 16
  end_topology: exponential
  seed: 72
